# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gke-policy
spec:
  shortDescription: Validates GKE clusters configuration
  homepage: https://github.com/google/gke-policy-automation
  description: |
    Tool and policy library for validating Google Kubernetes Engine clusters
    against the configuration best practices and scalability limits.
  caveats: |
    The plugin requires Google Cloud credentials to work.
    Use "gcloud auth application-default login" command to authenticate or
    specify credentials file as an argument.
  version: {{ .TagName }}
  platforms:
    - bin: gke-policy
      selector:
        matchLabels:
          os: linux
          arch: arm
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_linux_arm.zip" .TagName }}
    - bin: gke-policy
      selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_linux_amd64.zip" .TagName }}
    - bin: gke-policy
      selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_linux_arm64.zip" .TagName }}
    - bin: gke-policy.exe
      selector:
        matchLabels:
          os: windows
          arch: 386
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_windows_386.zip" .TagName }}
    - bin: gke-policy.exe
      selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_windows_amd64.zip" .TagName }}
    - bin: gke-policy
      selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_darwin_amd64.zip" .TagName }}
    - bin: gke-policy
      selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/google/gke-policy-automation/releases/download/{{ .TagName }}/gke-policy-automation_{{ .TagName }}_darwin_arm64.zip" .TagName }}
